const i18Obj = {
  'en': {
    // Header
    'home': 'Home',
    'catalog': 'Catalog',
    'favorites': 'Favorites',
    'cart': 'Cart',
    'feedback': 'Feedback',
    'sign-in': 'Sign in',
    'sign-up': 'Sign up',
    'profile': 'Profile',
    'admin-panel': 'Admin Panel',
    'logout': 'Logout',
    
    // Hero section
    'hero-title': 'Professional Digital Solutions for Your Business',
    'hero-subtitle': 'We provide comprehensive digital services to help your business grow and succeed in the modern digital landscape.',
    'start-trial': 'Start free trial',
    'learn-more': 'Learn more',
    
    // Features section
    'features-title': 'Transform Your Digital Presence',
    'features-subtitle': 'Our comprehensive suite of services is designed to elevate your business in the digital world.',
    'feature-1-title': 'Web Development',
    'feature-1-text': 'Custom websites and web applications built with modern technologies for optimal performance and user experience.',
    'feature-2-title': 'Digital Marketing',
    'feature-2-text': 'Strategic marketing campaigns that drive traffic, increase conversions, and grow your online presence.',
    'feature-3-title': 'Mobile Applications',
    'feature-3-text': 'Native and cross-platform mobile apps that provide seamless experiences across all devices.',
    'feature-4-title': 'UI/UX Design',
    'feature-4-text': 'Beautiful and intuitive designs that engage users and enhance brand perception.',
    'feature-5-title': 'SEO Optimization',
    'feature-5-text': 'Comprehensive SEO strategies to improve search rankings and increase organic traffic.',
    'feature-6-title': 'Cloud Solutions',
    'feature-6-text': 'Scalable cloud infrastructure and services to support your business growth and operations.',
    
    // Solutions section
    'solutions-tag': 'Digital Excellence',
    'solutions-title': 'Tailored Solutions for Every Business',
    'solutions-subtitle': 'We create custom digital strategies that align with your specific business goals and objectives.',
    'solution-label': 'E-commerce Solutions',
    'solution-title': 'Boost Your Online Sales',
    'solution-text': 'Complete e-commerce platforms with secure payment processing, inventory management, and customer analytics.',
    'solution-item-1': 'Custom shopping cart implementation',
    'solution-item-2': 'Secure payment gateway integration',
    'solution-item-3': 'Advanced inventory management system',
    
    // Second solution
    'solution-label-2': 'Enterprise Platforms',
    'solution-title-2': 'Streamline Your Operations',
    'solution-text-2': 'Robust enterprise solutions that automate processes and improve organizational efficiency.',
    'solution-item-2-1': 'Custom CRM development',
    'solution-item-2-2': 'Workflow automation systems',
    'solution-item-2-3': 'Real-time analytics dashboard',
    
    // Third solution
    'solution-label-3': 'Startup Launch',
    'solution-title-3': 'Launch Your Idea Successfully',
    'solution-text-3': 'End-to-end solutions for startups from initial concept to market launch and beyond.',
    'solution-item-3-1': 'MVP development and testing',
    'solution-item-3-2': 'Market research and validation',
    'solution-item-3-3': 'Growth strategy implementation',
    
    // Testimonials section
    'testimonials-title': 'Client Success Stories',
    'testimonials-subtitle': 'See how we\'ve helped businesses transform their digital presence and achieve remarkable results.',
    'testimonial-1-quote': 'Their team transformed our outdated website into a modern, user-friendly platform that increased our conversion rate by 45%. The attention to detail and customer service were exceptional.',
    'testimonial-1-author': 'Sarah Johnson',
    'testimonial-1-company': '/ TechForward Inc.',
    'testimonial-2-quote': 'The mobile app they developed for our retail business has been a game-changer. Our sales increased by 60% in the first quarter post-launch, and customer engagement is at an all-time high.',
    'testimonial-2-author': 'Michael Rodriguez',
    'testimonial-2-company': '/ Retail Dynamics',
    'testimonial-3-quote': 'Working with them on our digital marketing strategy has been transformative. We\'ve seen a 300% increase in qualified leads and significantly improved our online brand presence.',
    'testimonial-3-author': 'Emily Chen',
    'testimonial-3-company': '/ Growth Solutions LLC',
    
    // Newsletter section
    'newsletter-title': 'Stay Updated',
    'newsletter-subtitle': 'Subscribe to our newsletter for the latest digital trends, tips, and exclusive offers.',
    'newsletter-placeholder': 'Enter your email address',
    'newsletter-button': 'Subscribe',
    
    // Footer section
    'footer-text': 'We provide innovative digital solutions that help businesses thrive in the modern digital landscape. Our team of experts is dedicated to delivering exceptional results.',
    'products-title': 'Services',
    'product-1': 'Web Development',
    'product-2': 'Mobile Apps',
    'product-3': 'Digital Marketing',
    'product-4': 'UI/UX Design',
    'product-5': 'SEO Services',
    'resources-title': 'Resources',
    'resource-1': 'Blog Articles',
    'resource-2': 'Case Studies',
    'resource-3': 'Webinars',
    'resource-4': 'Documentation',
    'company-title': 'Company',
    'company-1': 'About Us',
    'company-2': 'Careers',
    'company-3': 'Contact',
    'company-4': 'Privacy Policy',
    'company-5': 'Terms of Service',
    'copyright': '© 2024 Digital Solutions Inc. All rights reserved.',
    
    // Language switcher
    'language-en': 'English',
    'language-ru': 'Russian',
    
    // Modal window
    'modal-title': 'User Settings',
    'user-info-title': 'Personal Information',
    'user-username': 'Username:',
    'user-email': 'Email:',
    'user-role': 'Role:',
    'user-joined': 'Member since:',
    'settings-title': 'Current Settings',
    'settings-language': 'Language:',
    'settings-theme': 'Theme:',
    'reset-settings': 'Reset Settings',
    'save-changes': 'Save Changes',
    'sign-in-to-view': 'Please sign in to view and edit your settings',
    'sign-in-button': 'Sign In',

    // Login page
    'login-title': 'Login - ServiceHub',
    'login-welcome': 'Welcome Back',
    'login-subtitle': 'Sign in to your account to continue',
    'login-email-label': 'Email or Username',
    'login-email-placeholder': 'email@example.com or username',
    'login-email-error': 'Please enter a valid email or username',
    'login-password-label': 'Password',
    'login-password-placeholder': 'Enter your password',
    'login-password-error': 'Please enter your password',
    'login-remember': 'Remember me',
    'login-forgot': 'Forgot password?',
    'login-button': 'Sign In',
    'login-no-account': 'Don\'t have an account? Sign up',
    'login-social-divider': 'Or sign in with',
    'login-google': 'Google',
    'login-github': 'GitHub',
    'login-facebook': 'Facebook',
    'login-success': 'Successfully signed in!',
    'login-error': 'Invalid email/username or password',
    
    // Forgot password modal
    'forgot-title': 'Reset Password',
    'forgot-description': 'Enter your email address and we\'ll send you instructions to reset your password.',
    'forgot-email-label': 'Email Address',
    'forgot-email-placeholder': 'your.email@example.com',
    'forgot-button': 'Send Reset Link',
    'forgot-success': 'Password reset link sent to your email',
    'forgot-error': 'Please enter a valid email address',
    
    // Validation messages
    'validation-required': 'This field is required',
    'validation-email': 'Please enter a valid email address',
    'validation-min-length': 'Must be at least {min} characters',
    'validation-max-length': 'Must be no more than {max} characters',
    
    // Error messages
    'error-network': 'Network error. Please check your connection',
    'error-server': 'Server error. Please try again later',
    'error-unknown': 'An unknown error occurred',
    
    // Success messages
    'success-operation': 'Operation completed successfully',
    'success-saved': 'Changes saved successfully',

    'register-title': 'Register - ServiceHub',
    'register-welcome': 'Create Account',
    'register-subtitle': 'Join our community and explore amazing services',
    'register-phone-label': 'Phone Number (Belarus only)',
    'register-phone-placeholder': '29 123 45 67',
    'register-phone-hint': 'Format: 29 123 45 67 or 291234567',
    'register-phone-error': 'Please enter a valid Belarusian phone number',
    'register-email-label': 'Email Address',
    'register-email-placeholder': 'your.email@example.com',
    'register-email-error': 'Please enter a valid email address',
    'register-birthdate-label': 'Date of Birth',
    'register-birthdate-hint': 'You must be at least 16 years old',
    'register-birthdate-error': 'You must be at least 16 years old',
    'register-firstname-label': 'First Name',
    'register-firstname-placeholder': 'John',
    'register-firstname-error': 'Please enter your first name (min 2 characters)',
    'register-lastname-label': 'Last Name',
    'register-lastname-placeholder': 'Doe',
    'register-lastname-error': 'Please enter your last name (min 2 characters)',
    'register-middlename-label': 'Middle Name (Optional)',
    'register-middlename-placeholder': 'Michael',
    'register-middlename-error': 'Please enter a valid middle name',
    'register-password-method-label': 'Password Method',
    'register-password-auto': 'Generate password automatically',
    'register-password-manual': 'Set my own password',
    'register-password-label': 'Password',
    'register-password-placeholder': 'Enter your password',
    'register-password-hint': 'Must contain: 8-20 chars, uppercase, lowercase, number, special character',
    'register-password-strength': 'Strength:',
    'register-password-weak': 'Weak',
    'register-password-medium': 'Medium',
    'register-password-strong': 'Strong',
    'register-password-very-strong': 'Very Strong',
    'register-password-error': 'Password must be 8-20 characters and include uppercase, lowercase, number, and special character',
    'register-confirm-password-label': 'Confirm Password',
    'register-confirm-password-placeholder': 'Repeat your password',
    'register-confirm-password-error': 'Passwords do not match',
    'register-generated-password-label': 'Generated Password',
    'register-generated-password-hint': 'Your password will be generated automatically. Save it securely!',
    'register-copy-password': 'Copy password',
    'register-regenerate-password': 'Regenerate password',
    'register-loading': 'Loading...',
    'register-copied': 'Copied!',
    'register-username-label': 'Username',
    'register-username-placeholder': 'e.g., JohnDoe123',
    'register-username-hint': 'Username will be generated automatically. You have 5 regeneration attempts.',
    'register-username-error': 'Please enter a valid username',
    'register-username-taken': 'This username is already taken',
    'register-username-available': 'Username available',
    'register-generate-button': 'Generate',
    'register-attempts-counter': 'Regeneration attempts left:',
    'register-terms-text': 'I agree to the',
    'register-terms-link': 'Terms of Service',
    'register-terms-and': 'and',
    'register-privacy-link': 'Privacy Policy',
    'register-terms-error': 'You must accept the terms and conditions',
    'register-button': 'Create Account',
    'register-button-disabled': 'Please fill all required fields',
    'register-login-link': 'Already have an account? Sign in',
    'register-success': 'Account created successfully!',
    'register-error': 'Error creating account. Please try again.',
    'register-error-phone-exists': 'Phone number already registered',
    'register-error-email-exists': 'Email already registered',
    
    // Terms modal
    'terms-title': 'Terms of Service',
    'terms-section-1-title': '1. Acceptance of Terms',
    'terms-section-1-text': 'By accessing and using ServiceHub, you accept and agree to be bound by the terms and provision of this agreement.',
    'terms-section-2-title': '2. User Responsibilities',
    'terms-section-2-text': 'Users are responsible for maintaining the confidentiality of their account and password.',
    'terms-section-3-title': '3. Service Modifications',
    'terms-section-3-text': 'ServiceHub reserves the right to modify or discontinue any service at any time.',
    'terms-section-4-title': '4. Limitation of Liability',
    'terms-section-4-text': 'ServiceHub shall not be liable for any indirect, incidental, or consequential damages.',
    'terms-last-updated': 'Last updated: December 2024',
    'terms-accept-button': 'I Accept',

    // Feedback page
    'feedback-title': 'Feedback - ServiceHub',
    'feedback-header': 'Customer Feedback',
    'feedback-subtitle': 'Share your experience with our services',
    'feedback-write-review': 'Write a Review',
    'feedback-form-description': 'Tell us about your experience with our services',
    'feedback-service-label': 'Select Service',
    'feedback-loading-services': 'Loading services...',
    'feedback-service-hint': 'You can only review services you have purchased',
    'feedback-service-error': 'Please select a service',
    'feedback-rating-label': 'Rating',
    'feedback-rating-default': 'Select your rating',
    'feedback-rating-5': 'Excellent - 5 stars',
    'feedback-rating-4': 'Very Good - 4 stars',
    'feedback-rating-3': 'Good - 3 stars',
    'feedback-rating-2': 'Fair - 2 stars',
    'feedback-rating-1': 'Poor - 1 star',
    'feedback-rating-error': 'Please select a rating',
    'feedback-title-label': 'Review Title',
    'feedback-title-placeholder': 'Brief summary of your experience',
    'feedback-title-error': 'Please enter a review title (max 100 characters)',
    'feedback-text-label': 'Detailed Review',
    'feedback-text-placeholder': 'Share your detailed experience with this service...',
    'feedback-text-error': 'Please enter a detailed review (50-1000 characters)',
    'feedback-text-hint': 'Be specific about what you liked or didn\'t like',
    'feedback-anonymous': 'Post as anonymous',
    'feedback-anonymous-hint': 'Your name will not be displayed',
    'feedback-submit-button': 'Submit Review',
    'feedback-submit-disabled': 'Please fill all required fields',
    'feedback-clear-button': 'Clear Form',
    'feedback-chars-counter': '/100 characters',
    'feedback-chars-counter-min': '/1000 characters (minimum 50)',
    'feedback-recent-reviews': 'Recent Reviews',
    'feedback-total-reviews': 'Total Reviews',
    'feedback-average-rating': 'Average Rating',
    'feedback-filter-service': 'Filter by Service:',
    'feedback-filter-rating': 'Filter by Rating:',
    'feedback-filter-all': 'All Services',
    'feedback-filter-all-ratings': 'All Ratings',
    'feedback-filter-rating-5': '5 Stars',
    'feedback-filter-rating-4': '4+ Stars',
    'feedback-filter-rating-3': '3+ Stars',
    'feedback-filter-rating-2': '2+ Stars',
    'feedback-filter-rating-1': '1 Star',
    'feedback-stars': 'Stars',
    'feedback-star': 'Star',
    'feedback-clear-filters': 'Clear Filters',
    'feedback-loading-reviews': 'Loading reviews...',
    'feedback-no-reviews-title': 'No reviews yet',
    'feedback-no-reviews-text': 'Be the first to share your experience!',
    'feedback-success': 'Review submitted successfully!',
    'feedback-error': 'Error submitting review. Please try again.',
    'feedback-error-not-purchased': 'You can only review services you have purchased',
    'feedback-error-duplicate': 'You have already reviewed this service',
    'feedback-delete-success': 'Review deleted successfully',
    'feedback-delete-error': 'Error deleting review',
    'feedback-edit-success': 'Review updated successfully',
    'feedback-edit-error': 'Error updating review',
    
    // Review card text
    'feedback-review-by': 'by',
    'feedback-review-anonymous': 'Anonymous User',
    'feedback-review-on': 'on',
    'feedback-review-service': 'Service:',
    'feedback-review-helpful': 'Helpful?',
    'feedback-review-helpful-count': 'people found this helpful',
    'feedback-review-reply': 'Reply from ServiceHub:',
    'feedback-review-edit': 'Edit',
    'feedback-review-delete': 'Delete',
    'feedback-review-report': 'Report',
    'feedback-review-load-more': 'Load More Reviews',
    'feedback-review-no-more': 'No more reviews to load',
    'feedback-review-sort-newest': 'Newest First',
    'feedback-review-sort-oldest': 'Oldest First',
    'feedback-review-sort-highest': 'Highest Rated',
    'feedback-review-sort-lowest': 'Lowest Rated',
    'feedback-review-sort-most-helpful': 'Most Helpful',
    
    // Date formatting
    'feedback-date-just-now': 'Just now',
    'feedback-date-minutes-ago': 'minutes ago',
    'feedback-date-hours-ago': 'hours ago',
    'feedback-date-days-ago': 'days ago',
    'feedback-date-weeks-ago': 'weeks ago',
    'feedback-date-months-ago': 'months ago',
    'feedback-date-years-ago': 'years ago',
    
    // Services list (for dropdown)
    'service-web-dev': 'Web Development',
    'service-mobile-app': 'Mobile Application',
    'service-digital-marketing': 'Digital Marketing',
    'service-ui-ux': 'UI/UX Design',
    'service-seo': 'SEO Optimization',
    'service-cloud': 'Cloud Solutions',
    'service-ecommerce': 'E-commerce Platform',
    'service-crm': 'CRM Development',
    'service-analytics': 'Business Analytics',

    // Favorites page
    'favorites-title': 'My Favorites - ServiceHub',
    'favorites-header': 'My Favorite Services',
    'favorites-subtitle': 'Services you\'ve saved for later',
    'favorites-clear-all': 'Clear All Favorites',
    'favorites-back-to-catalog': 'Back to Catalog',
    'favorites-loading': 'Loading favorites...',
    'favorites-empty-title': 'No favorites yet',
    'favorites-empty-text': 'Browse our catalog and add services to your favorites!',
    'favorites-empty-button': 'Browse Catalog',
    'favorites-remove': 'Remove from Favorites',
    'favorites-add-to-cart': 'Add to Cart',
    'favorites-view-details': 'View Details',
    'favorites-service-price': 'Price:',
    'favorites-service-rating': 'Rating:',
    'favorites-service-category': 'Category:',
    'favorites-service-duration': 'Duration:',
    'favorites-confirm-clear': 'Are you sure you want to remove all items from favorites?',
    'favorites-clear-success': 'All favorites have been cleared',
    'favorites-clear-error': 'Error clearing favorites',
    'favorites-remove-success': 'Service removed from favorites',
    'favorites-remove-error': 'Error removing service',
    'favorites-add-cart-success': 'Service added to cart',
    'favorites-add-cart-error': 'Error adding to cart',
    
    // Service categories
    'category-web-development': 'Web Development',
    'category-mobile-apps': 'Mobile Applications',
    'category-digital-marketing': 'Digital Marketing',
    'category-design': 'Design',
    'category-seo': 'SEO & Analytics',
    'category-cloud': 'Cloud Services',
    'category-consulting': 'Consulting',
    'category-support': 'Support & Maintenance',
    
    // Price and duration
    'price-hourly': '/hour',
    'price-project': '/project',
    'price-monthly': '/month',
    'duration-hours': 'hours',
    'duration-days': 'days',
    'duration-weeks': 'weeks',
    'duration-months': 'months',

    // Catalog page
    'catalog-title': 'Service Catalog - ServiceHub',
    'catalog-header': 'Our Service Catalog',
    'catalog-subtitle': 'Discover professional services tailored for your business needs',
    'catalog-filter-category': 'Filter by Category',
    'catalog-search-placeholder': 'Search services by name or description...',
    'catalog-sort-label': 'Sort by:',
    'catalog-sort-default': 'Default',
    'catalog-sort-name-asc': 'Name (A-Z)',
    'catalog-sort-name-desc': 'Name (Z-A)',
    'catalog-sort-price-asc': 'Price (Low to High)',
    'catalog-sort-price-desc': 'Price (High to Low)',
    'catalog-sort-rating-desc': 'Rating (High to Low)',
    'catalog-advanced-filters': 'Advanced Filters',
    'catalog-price-range': 'Price Range:',
    'catalog-min-price': 'Min $',
    'catalog-max-price': 'Max $',
    'catalog-price-to': 'to',
    'catalog-min-rating': 'Minimum Rating:',
    'catalog-rating-any': 'Any Rating',
    'catalog-rating-35': '3.5+ Stars',
    'catalog-rating-40': '4.0+ Stars',
    'catalog-rating-45': '4.5+ Stars',
    'catalog-rating-5': '5 Stars Only',
    'catalog-apply-filters': 'Apply Filters',
    'catalog-reset-filters': 'Reset',
    'catalog-showing': 'Showing',
    'catalog-of': 'of',
    'catalog-services': 'services',
    'catalog-page': 'Page',
    'catalog-previous': 'Previous',
    'catalog-next': 'Next',
    'catalog-items-6': '6 per page',
    'catalog-items-9': '9 per page',
    'catalog-items-12': '12 per page',
    'catalog-items-15': '15 per page',
    'catalog-loading': 'Loading services...',
    'catalog-no-results-title': 'No services found',
    'catalog-no-results-text': 'Try adjusting your search or filter criteria',
    'catalog-reset-all': 'Reset All Filters',
    'catalog-add-to-favorites': 'Add to Favorites',
    'catalog-remove-from-favorites': 'Remove from Favorites',
    'catalog-add-to-cart': 'Add to Cart',
    'catalog-view-details': 'View Details',
    'catalog-price': 'Price:',
    'catalog-rating': 'Rating:',
    'catalog-category': 'Category:',
    'catalog-duration': 'Duration:',
    'catalog-estimated': 'Estimated',
    'catalog-hours': 'hours',
    'catalog-days': 'days',
    'catalog-weeks': 'weeks',
    'catalog-popular': 'Popular',
    'catalog-featured': 'Featured',
    'catalog-new': 'New',
    'catalog-discount': 'Discount',
    'catalog-clear-search': 'Clear search',
    'catalog-applied-filters': 'Applied Filters:',
    'catalog-clear-all': 'Clear All',
    'catalog-price-filter': 'Price',
    'catalog-rating-filter': 'Rating',
    'catalog-category-filter': 'Category',
    
    // Service categories for catalog
    'category-all': 'All Categories',
    'category-web-dev': 'Web Development',
    'category-mobile-app': 'Mobile Applications',
    'category-digital-marketing': 'Digital Marketing',
    'category-ui-ux': 'UI/UX Design',
    'category-seo': 'SEO Optimization',
    'category-cloud': 'Cloud Solutions',
    'category-ecommerce': 'E-commerce',
    'category-crm': 'CRM Development',
    'category-analytics': 'Business Analytics',
    'category-consulting': 'IT Consulting',
    'category-support': 'Technical Support',
    
    // Service card text
    'service-starts-at': 'Starts at',
    'service-per-hour': '/hour',
    'service-per-project': '/project',
    'service-per-month': '/month',
    'service-features': 'Key Features:',
    'service-delivery': 'Delivery Time:',
    'service-revisions': 'Revisions Included:',
    'service-support': 'Support:',
    'service-guarantee': 'Money-back Guarantee',
    'service-included': 'What\'s Included',
    'service-not-included': 'Not Included',
    'service-requirements': 'Requirements',
    'service-faq': 'FAQ',
    'service-reviews': 'Reviews',
    'service-order-now': 'Order Now',
    'service-contact-seller': 'Contact Seller',
    'service-save-for-later': 'Save for Later',
    'service-share': 'Share',
    'service-report': 'Report',
    
    // Price packages
    'package-basic': 'Basic',
    'package-standard': 'Standard',
    'package-premium': 'Premium',
    'package-enterprise': 'Enterprise',
    'package-features': 'Features',
    'package-select': 'Select Package',
    
    // Success/error messages
    'catalog-favorite-added': 'Service added to favorites',
    'catalog-favorite-removed': 'Service removed from favorites',
    'catalog-cart-added': 'Service added to cart',
    'catalog-cart-error': 'Error adding to cart',
    'catalog-load-error': 'Error loading services',
    'catalog-filter-applied': 'Filters applied',
    'catalog-filter-reset': 'Filters reset',
    'catalog-search-cleared': 'Search cleared',

    // Cart page
    'cart-title': 'Shopping Cart - ServiceHub',
    'cart-header': 'Shopping Cart',
    'cart-subtitle': 'Review and manage your selected services',
    'cart-clear-all': 'Clear Cart',
    'cart-add-more': 'Add More Services',
    'cart-loading': 'Loading cart items...',
    'cart-order-summary': 'Order Summary',
    'cart-subtotal': 'Subtotal',
    'cart-tax': 'Tax (10%)',
    'cart-total': 'Total',
    'cart-checkout': 'Proceed to Checkout',
    'cart-secure': 'Secure checkout',
    'cart-empty-title': 'Your cart is empty',
    'cart-empty-text': 'Add some amazing services to get started!',
    'cart-browse-services': 'Browse Services',
    'cart-item-remove': 'Remove',
    'cart-item-quantity': 'Quantity',
    'cart-item-price': 'Price',
    'cart-item-total': 'Total',
    'cart-item-duration': 'Duration',
    'cart-item-service': 'Service',
    'cart-item-category': 'Category',
    'cart-item-rating': 'Rating',
    'cart-item-edit': 'Edit',
    'cart-item-save': 'Save for later',
    'cart-item-move-to-favorites': 'Move to Favorites',
    'cart-increase': 'Increase',
    'cart-decrease': 'Decrease',
    'cart-confirm-remove': 'Remove this item from cart?',
    'cart-confirm-clear': 'Clear all items from cart?',
    'cart-remove-success': 'Item removed from cart',
    'cart-clear-success': 'Cart cleared successfully',
    'cart-update-success': 'Cart updated successfully',
    'cart-error': 'Error updating cart',
    'cart-empty-checkout': 'Cart is empty. Add items to proceed.',
    'cart-login-required': 'Please login to proceed with checkout',
    'cart-checkout-success': 'Checkout successful!',
    'cart-checkout-error': 'Error during checkout',
    
    // Checkout modal
    'cart-modal-title': 'Order Confirmed!',
    'cart-modal-thanks': 'Thank you for your purchase!',
    'cart-modal-message': 'Your order has been successfully processed. A confirmation email has been sent to your email address.',
    'cart-modal-order-id': 'Order ID:',
    'cart-modal-total': 'Total Amount:',
    'cart-modal-delivery': 'Estimated Delivery:',
    'cart-modal-delivery-time': 'Within 5-7 business days',
    'cart-modal-continue': 'Continue Shopping',
    'cart-modal-view': 'View Order Details',
    
    // Payment methods
    'payment-credit-card': 'Credit Card',
    'payment-paypal': 'PayPal',
    'payment-bank-transfer': 'Bank Transfer',
    'payment-crypto': 'Cryptocurrency',
    'payment-select-method': 'Select Payment Method',
    'payment-card-number': 'Card Number',
    'payment-card-expiry': 'Expiry Date',
    'payment-card-cvv': 'CVV',
    'payment-card-name': 'Name on Card',
    'payment-billing-address': 'Billing Address',
    'payment-shipping-address': 'Shipping Address',
    'payment-same-as-billing': 'Same as billing address',
    'payment-terms': 'I agree to the terms and conditions',
    'payment-place-order': 'Place Order',
    'payment-processing': 'Processing payment...',
    
    // Order status
    'order-status-pending': 'Pending',
    'order-status-processing': 'Processing',
    'order-status-completed': 'Completed',
    'order-status-cancelled': 'Cancelled',
    'order-status-refunded': 'Refunded',
    'order-date': 'Order Date',
    'order-status': 'Order Status',
    'order-tracking': 'Tracking Number',
    'order-invoice': 'Download Invoice',
    
    // Shipping options
    'shipping-standard': 'Standard (5-7 business days)',
    'shipping-express': 'Express (2-3 business days)',
    'shipping-overnight': 'Overnight (1 business day)',
    'shipping-free': 'Free Shipping',
    'shipping-calculating': 'Calculating shipping...',
    'shipping-select': 'Select Shipping Method',
    
    // Discount codes
    'discount-apply': 'Apply Discount Code',
    'discount-code': 'Discount Code',
    'discount-apply-btn': 'Apply',
    'discount-remove': 'Remove',
    'discount-invalid': 'Invalid discount code',
    'discount-applied': 'Discount applied',
    'discount-expired': 'Discount code expired',

    // Admin page
    'admin-title': 'Admin Panel - ServiceHub',
    'admin-access-denied-title': 'Access Denied',
    'admin-access-denied-text': 'This area is restricted to administrators only.',
    'admin-back-to-home': 'Back to Home',
    'admin-header': 'Admin Dashboard',
    'admin-subtitle': 'Manage services, feedback, orders, and users',
    'admin-total-services': 'Total Services',
    'admin-total-orders': 'Total Orders',
    'admin-total-reviews': 'Total Reviews',
    'admin-total-users': 'Total Users',
    'admin-tab-services': 'Services',
    'admin-tab-feedback': 'Feedback',
    'admin-tab-orders': 'Orders',
    'admin-tab-users': 'Users',
    'admin-services-title': 'Services Management',
    'admin-add-service': 'Add New Service',
    'admin-search-services': 'Search services...',
    'admin-feedback-title': 'Feedback Management',
    'admin-filter-service': 'Filter by Service:',
    'admin-filter-user': 'Filter by User:',
    'admin-filter-rating': 'Filter by Rating:',
    'admin-filter-all': 'All',
    'admin-stars': 'Stars',
    'admin-star': 'Star',
    'admin-orders-title': 'Orders Management',
    'admin-users-title': 'Users Management',
    'admin-role-admin': 'Administrators',
    'admin-role-user': 'Regular Users',
    'admin-modal-add-service': 'Add New Service',
    'admin-modal-edit-service': 'Edit Service',
    'admin-service-name': 'Service Name',
    'admin-service-name-placeholder': 'Web Design',
    'admin-service-category': 'Category',
    'admin-select-category': 'Select category',
    'admin-service-price': 'Price ($)',
    'admin-service-price-placeholder': '299',
    'admin-service-rating': 'Rating (1-5)',
    'admin-service-rating-placeholder': '4.7',
    'admin-service-description': 'Description',
    'admin-service-description-placeholder': 'Describe the service...',
    'admin-chars-counter': '/500 characters',
    'admin-service-image': 'Image URL',
    'admin-service-image-placeholder': '../assets/solution1.png',
    'admin-service-image-hint': 'Use relative path or full URL',
    'admin-save-service': 'Save Service',
    'admin-cancel': 'Cancel',
    'admin-edit': 'Edit',
    'admin-delete': 'Delete',
    'admin-view': 'View',
    'admin-confirm-delete': 'Are you sure you want to delete this item?',
    'admin-delete-success': 'Item deleted successfully',
    'admin-delete-error': 'Error deleting item',
    'admin-save-success': 'Item saved successfully',
    'admin-save-error': 'Error saving item',
    'admin-load-error': 'Error loading data',
    'admin-status-active': 'Active',
    'admin-status-inactive': 'Inactive',
    'admin-status-pending': 'Pending',
    'admin-status-completed': 'Completed',
    'admin-status-cancelled': 'Cancelled',
    'admin-no-data': 'No data available',
    'admin-loading': 'Loading...',
    'admin-actions': 'Actions',
    'admin-user-id': 'User ID',
    'admin-user-email': 'Email',
    'admin-user-role': 'Role',
    'admin-user-created': 'Created',
    'admin-order-id': 'Order ID',
    'admin-order-customer': 'Customer',
    'admin-order-date': 'Order Date',
    'admin-order-status': 'Status',
    'admin-order-total': 'Total',
    'admin-feedback-id': 'Feedback ID',
    'admin-feedback-service': 'Service',
    'admin-feedback-user': 'User',
    'admin-feedback-rating': 'Rating',
    'admin-feedback-date': 'Date',
    'admin-service-id': 'Service ID',
    'admin-service-image': 'Image',
    'admin-service-price': 'Price',
    'admin-service-rating': 'Rating',
    
    // Admin categories
    'category-design': 'Design',
    'category-development': 'Development',
    'category-marketing': 'Marketing',
    'category-consulting': 'Consulting',
    'category-analytics': 'Analytics',
    'category-support': 'Support',
    'category-security': 'Security',
    'category-cloud': 'Cloud',
    'category-ai': 'AI',
    
    // Validation messages
    'admin-validation-required': 'This field is required',
    'admin-validation-price': 'Please enter a valid price',
    'admin-validation-rating': 'Rating must be between 0 and 5',
    'admin-validation-url': 'Please enter a valid URL',
    'admin-validation-description': 'Description must be between 10 and 500 characters',

'admin-view-feedback': 'View Feedback',
'admin-no-results': 'No results found',
'admin-try-adjusting-criteria': 'Try adjusting your search criteria',
'admin-service-meta': 'Service Meta',
'admin-id': 'ID',
'admin-service-feedback-count': 'Feedback',
'admin-feedback-details': 'Feedback Details',
'admin-no-feedback-yet': 'No Feedback Yet',
'admin-feedback-header': 'Feedback for:',
'admin-total-reviews-for-service': 'Total reviews:',
'admin-user-info': 'User Info',
'admin-feedback-text': 'Feedback Text',
'admin-feedback-meta': 'Feedback Meta',
'admin-reported': 'Reported',
'admin-order-info': 'Order Info',
'admin-customer': 'Customer',
'admin-phone': 'Phone',
'admin-order-items': 'Items',
'admin-order-item': 'Item',
'admin-order-total': 'Total:',
'admin-user-stats': 'User Stats',
'admin-reviews': 'reviews',
'admin-orders': 'orders',
'admin-spent': 'spent',
'admin-change-role': 'Change Role',
'admin-generate': 'Generate',
'admin-regenerate': 'Regenerate',
'admin-attempts-left': 'Regeneration attempts left:',
'admin-copied': 'Copied!',
'admin-service-image-hint': 'Use relative path (e.g., ../assets/service.jpg) or full URL',
'admin-validation-image-url': 'Please enter a valid image URL',
'admin-validation-name': 'Service name must be at least 3 characters',
'admin-validation-description-min': 'Description must be at least 10 characters',
'admin-service-saved': 'Service saved successfully',
'admin-service-deleted': 'Service deleted successfully',
'admin-feedback-deleted': 'Feedback deleted successfully',
'admin-user-role-changed': 'User role changed successfully',
'admin-user-deleted': 'User deleted successfully',
'admin-cannot-delete-admin': 'Cannot delete administrator users',
'admin-delete-user-confirm': 'This user has order history. Deleting them will also delete their orders. Continue?',
'admin-delete-service-confirm': 'This service has {count} feedback entries. Deleting it will also delete all associated feedback. Continue?',
'admin-saving': 'Saving...',
'admin-loading-data': 'Loading data...',
'admin-access-checking': 'Checking access...',
'admin-auth-unavailable': 'Authentication service not available',
'admin-data-load-failed': 'Failed to load data',
'admin-form-invalid': 'Please fix validation errors',
'admin-operation-failed': 'Operation failed',
'admin-close': 'Close',
'admin-confirm': 'Confirm',
'admin-yes': 'Yes',
'admin-no': 'No',
'admin-retry': 'Retry',

'admin-category-web-development': 'Web Development',
'admin-category-mobile-apps': 'Mobile Applications',
'admin-category-digital-marketing': 'Digital Marketing',
'admin-category-ui-ux-design': 'UI/UX Design',
'admin-category-seo': 'SEO & Analytics',
'admin-category-cloud-services': 'Cloud Services',
'admin-category-consulting': 'Consulting',
'admin-category-support': 'Support',

'logout-success': 'Logged out successfully',
'login-failed': 'Login failed. Please try again.',
'registration-failed': 'Registration failed. Please try again.',
'welcome-back': 'Welcome back, {name}!',
'account-created': 'Account created successfully!',

'cart-item-not-found': 'Cart item not found',
'cart-empty': 'Cart is already empty',
'cart-not-implemented': 'Order details would show here',
'cart-item-price': 'Price',
'cart-item-remove': 'Remove',
'cart-item-category': 'Category',
'cart-item-quantity': 'Quantity',
'cart-item-total': 'Total',
'cart-item-duration': 'Duration',
'cart-item-service': 'Service',
'cart-item-rating': 'Rating',
'cart-increase': 'Increase',
'cart-decrease': 'Decrease',

'catalog-login-required': 'Please sign in to add to favorites',
'catalog-login-required-cart': 'Please sign in to add to cart',
'catalog-in-cart': 'In Cart',
'catalog-service-details': 'Details for service',
'catalog-favorite-error': 'Failed to update favorites',
'catalog-remove-from-favorites': 'Remove from favorites',
'catalog-add-to-favorites': 'Add to favorites',
'catalog-loading': 'Loading services...',
'catalog-sort-name_asc': 'Name (A-Z)',
'catalog-sort-name_desc': 'Name (Z-A)',
'catalog-sort-price_asc': 'Price (Low to High)',
'catalog-sort-price_desc': 'Price (High to Low)',
'catalog-sort-rating_desc': 'Rating (High to Low)',
'catalog-sort-default': 'Default',
'catalog-rating-0': 'Any Rating',
'catalog-rating-35': '3.5+ Stars',
'catalog-rating-40': '4.0+ Stars',
'catalog-rating-45': '4.5+ Stars',
'catalog-rating-5': '5 Stars Only',
'catalog-items-6': '6 per page',
'catalog-items-9': '9 per page',
'catalog-items-12': '12 per page',
'catalog-items-15': '15 per page',

'favorites-login-required': 'Please sign in to add to cart',
'favorites-confirm-remove': 'Remove this service from favorites?',
'favorites-confirm-clear': 'Are you sure you want to remove all favorites?',
'favorites-empty': 'No favorites to clear',
'favorites-back-to-catalog': 'Back to Catalog',
'favorites-remove': 'Remove',
'favorites-add-to-cart': 'Add to Cart',
'favorites-view-details': 'View Details',
'favorites-service-price': 'Price:',
'favorites-service-rating': 'Rating:',
'favorites-service-category': 'Category:',
'favorites-service-duration': 'Duration:',
'favorites-loading': 'Loading favorites...',
'favorites-remove-tooltip': 'Remove from favorites',

'feedback-load-error': 'Failed to load data',
'feedback-no-purchased-services': 'No purchased services',
'feedback-service-default': 'Select a service',
'feedback-sign-in-required': 'Please sign in to leave feedback',
'feedback-admin-restricted': 'Administrators cannot leave feedback',
'feedback-purchase-required': 'You need to purchase a service first',
'feedback-submitting': 'Submitting...',
'feedback-form-invalid': 'Please fix all errors before submitting',
'feedback-unknown-service': 'Unknown Service',
'feedback-customer': 'Customer',
'feedback-login-required-helpful': 'Please sign in to mark as helpful',
'feedback-helpful-success': 'Marked as helpful!',
'feedback-helpful-error': 'Failed to update',
'feedback-confirm-delete': 'Are you sure you want to delete this feedback?',
'feedback-loading-services': 'Loading services...',
'feedback-service-hint': 'You can only review services you have purchased',
'feedback-text-hint': 'Be specific about what you liked or didn\'t like',
'feedback-submit-disabled': 'Please fill all required fields',
'feedback-stars': 'stars',
'feedback-star': 'star',
'feedback-loading-reviews': 'Loading reviews...',

'login-toggle-password': 'Show/Hide password',
'login-password-show': 'Show password',
'login-password-hide': 'Hide password',
'login-signing-in': 'Signing in...',
'login-social-not-implemented': '{provider} login would be implemented here',
'forgot-sending': 'Sending...',

'register-password-show': 'Show password',
'register-password-hide': 'Hide password',
'register-phone-operator-error': 'Must be a valid Belarusian mobile number (29, 33, 44, 25)',
'register-name-format-error': 'Name can only contain letters, spaces, hyphens, and apostrophes',
'register-password-length-error': 'Password must be 8-20 characters long',
'register-password-common-error': 'This password is too common. Choose a stronger one.',
'register-password-uppercase': 'Uppercase letter required. ',
'register-password-lowercase': 'Lowercase letter required. ',
'register-password-number': 'Number required. ',
'register-password-special': 'Special character (@$!%*?&) required. ',
'register-username-length-error': 'Username must be 3-20 characters',
'register-username-format-error': 'Only letters, numbers, and underscores allowed',
'register-name-required': 'Please enter your first and last name first',
'register-no-attempts-left': 'No attempts left. You can now enter your own username.',
'register-attempts-hint': 'Username generated automatically. You have {attempts} regeneration attempts.',
'register-manual-username-placeholder': 'Enter your own username',
'register-manual-enabled': 'Manual Input Enabled',
'register-manual-hint': 'You can now enter your own username. Make sure it\'s unique!',
'register-creating': 'Creating Account...',
'register-form-invalid': 'Please fix all errors before submitting',
'register-copy-error': 'Failed to copy password',

'theme-light': 'Light theme',
'theme-dark': 'Dark theme',
'theme-activated': '{theme} activated',
'settings-reset-confirm': 'Are you sure you want to reset all settings to default?',
'settings-reset-success': 'Settings have been reset to default',
'settings-language': 'Language:',
'settings-theme': 'Theme:',
'theme-light': 'Light',
'theme-dark': 'Dark',

'user-settings': 'User settings',
'user-username-placeholder': 'Enter username',
'user-email-placeholder': 'Enter email',
'unknown-date': 'Unknown',
'change-language': 'Change Language',
'change-theme': 'Change Theme',
'sign-in-to-save': 'Please sign in to save settings',
'username-min-length': 'Username must be at least 3 characters',
'settings-saved': 'Settings saved successfully',
'sign-in-to-reset': 'Please sign in to reset settings',
'settings-reset-success': 'All settings have been reset to default',
  },
  
  'ru': {
    // Header
    'home': 'Главная',
    'catalog': 'Каталог',
    'favorites': 'Избранное',
    'cart': 'Корзина',
    'feedback': 'Отзывы',
    'sign-in': 'Войти',
    'sign-up': 'Регистрация',
    'profile': 'Профиль',
    'admin-panel': 'Админ панель',
    'logout': 'Выйти',
    
    // Hero section
    'hero-title': 'Профессиональные цифровые решения для вашего бизнеса',
    'hero-subtitle': 'Мы предоставляем комплексные цифровые услуги, которые помогут вашему бизнесу расти и развиваться в современной цифровой среде.',
    'start-trial': 'Начать бесплатно',
    'learn-more': 'Подробнее',
    
    // Features section
    'features-title': 'Преобразуйте ваше цифровое присутствие',
    'features-subtitle': 'Наш комплекс услуг разработан для повышения эффективности вашего бизнеса в цифровом мире.',
    'feature-1-title': 'Веб-разработка',
    'feature-1-text': 'Индивидуальные веб-сайты и приложения, созданные с использованием современных технологий для оптимальной производительности и удобства пользователей.',
    'feature-2-title': 'Цифровой маркетинг',
    'feature-2-text': 'Стратегические маркетинговые кампании, которые увеличивают трафик, повышают конверсию и усиливают онлайн-присутствие.',
    'feature-3-title': 'Мобильные приложения',
    'feature-3-text': 'Нативные и кроссплатформенные мобильные приложения, обеспечивающие бесшовный опыт на всех устройствах.',
    'feature-4-title': 'UI/UX дизайн',
    'feature-4-text': 'Красивый и интуитивно понятный дизайн, который привлекает пользователей и улучшает восприятие бренда.',
    'feature-5-title': 'SEO оптимизация',
    'feature-5-text': 'Комплексные SEO стратегии для улучшения позиций в поиске и увеличения органического трафика.',
    'feature-6-title': 'Облачные решения',
    'feature-6-text': 'Масштабируемая облачная инфраструктура и сервисы для поддержки роста и операций вашего бизнеса.',
    
    // Solutions section
    'solutions-tag': 'Цифровое превосходство',
    'solutions-title': 'Индивидуальные решения для каждого бизнеса',
    'solutions-subtitle': 'Мы создаем индивидуальные цифровые стратегии, соответствующие вашим бизнес-целям и задачам.',
    'solution-label': 'E-commerce решения',
    'solution-title': 'Увеличьте онлайн-продажи',
    'solution-text': 'Полноценные платформы для электронной коммерции с безопасной обработкой платежей, управлением запасами и аналитикой клиентов.',
    'solution-item-1': 'Индивидуальная реализация корзины покупок',
    'solution-item-2': 'Интеграция безопасных платежных шлюзов',
    'solution-item-3': 'Продвинутая система управления запасами',
    
    // Second solution
    'solution-label-2': 'Корпоративные платформы',
    'solution-title-2': 'Оптимизируйте свои операции',
    'solution-text-2': 'Надежные корпоративные решения для автоматизации процессов и повышения эффективности организации.',
    'solution-item-2-1': 'Разработка индивидуальной CRM',
    'solution-item-2-2': 'Системы автоматизации рабочих процессов',
    'solution-item-2-3': 'Панель аналитики в реальном времени',
    
    // Third solution
    'solution-label-3': 'Запуск стартапа',
    'solution-title-3': 'Успешно запустите свою идею',
    'solution-text-3': 'Комплексные решения для стартапов: от первоначальной концепции до запуска на рынок и далее.',
    'solution-item-3-1': 'Разработка и тестирование MVP',
    'solution-item-3-2': 'Исследование рынка и валидация',
    'solution-item-3-3': 'Реализация стратегии роста',
    
    // Testimonials section
    'testimonials-title': 'Истории успеха клиентов',
    'testimonials-subtitle': 'Узнайте, как мы помогли компаниям преобразовать их цифровое присутствие и достичь выдающихся результатов.',
    'testimonial-1-quote': 'Их команда превратила наш устаревший сайт в современную, удобную платформу, которая увеличила нашу конверсию на 45%. Внимание к деталям и обслуживание клиентов были исключительными.',
    'testimonial-1-author': 'Сара Джонсон',
    'testimonial-1-company': '/ TechForward Inc.',
    'testimonial-2-quote': 'Мобильное приложение, которое они разработали для нашего ритейл-бизнеса, изменило правила игры. Наши продажи выросли на 60% в первом квартале после запуска, а вовлеченность клиентов достигла рекордного уровня.',
    'testimonial-2-author': 'Михаил Родригес',
    'testimonial-2-company': '/ Retail Dynamics',
    'testimonial-3-quote': 'Сотрудничество с ними по нашей цифровой маркетинговой стратегии было преобразующим. Мы увидели увеличение квалифицированных лидов на 300% и значительно улучшили наше онлайн-присутствие бренда.',
    'testimonial-3-author': 'Эмили Чен',
    'testimonial-3-company': '/ Growth Solutions LLC',
    
    // Newsletter section
    'newsletter-title': 'Будьте в курсе',
    'newsletter-subtitle': 'Подпишитесь на нашу рассылку, чтобы получать последние цифровые тренды, советы и эксклюзивные предложения.',
    'newsletter-placeholder': 'Введите ваш email',
    'newsletter-button': 'Подписаться',
    
    // Footer section
    'footer-text': 'Мы предоставляем инновационные цифровые решения, которые помогают бизнесу процветать в современной цифровой среде. Наша команда экспертов стремится предоставлять исключительные результаты.',
    'products-title': 'Услуги',
    'product-1': 'Веб-разработка',
    'product-2': 'Мобильные приложения',
    'product-3': 'Цифровой маркетинг',
    'product-4': 'UI/UX дизайн',
    'product-5': 'SEO услуги',
    'resources-title': 'Ресурсы',
    'resource-1': 'Статьи в блоге',
    'resource-2': 'Кейсы',
    'resource-3': 'Вебинары',
    'resource-4': 'Документация',
    'company-title': 'Компания',
    'company-1': 'О нас',
    'company-2': 'Карьера',
    'company-3': 'Контакты',
    'company-4': 'Политика конфиденциальности',
    'company-5': 'Условия обслуживания',
    'copyright': '© 2024 Digital Solutions Inc. Все права защищены.',
    
    // Language switcher
    'language-en': 'Английский',
    'language-ru': 'Русский',
    
    // Modal window
    'modal-title': 'Настройки пользователя',
    'user-info-title': 'Личная информация',
    'user-username': 'Имя пользователя:',
    'user-email': 'Email:',
    'user-role': 'Роль:',
    'user-joined': 'Участник с:',
    'settings-title': 'Текущие настройки',
    'settings-language': 'Язык:',
    'settings-theme': 'Тема:',
    'reset-settings': 'Сбросить настройки',
    'save-changes': 'Сохранить изменения',
    'sign-in-to-view': 'Пожалуйста, войдите, чтобы просмотреть и изменить свои настройки',
    'sign-in-button': 'Войти',

    // Login page
    'login-title': 'Вход - ServiceHub',
    'login-welcome': 'С возвращением',
    'login-subtitle': 'Войдите в свой аккаунт, чтобы продолжить',
    'login-email-label': 'Email или Имя пользователя',
    'login-email-placeholder': 'email@example.com или имя пользователя',
    'login-email-error': 'Пожалуйста, введите корректный email или имя пользователя',
    'login-password-label': 'Пароль',
    'login-password-placeholder': 'Введите ваш пароль',
    'login-password-error': 'Пожалуйста, введите ваш пароль',
    'login-remember': 'Запомнить меня',
    'login-forgot': 'Забыли пароль?',
    'login-button': 'Войти',
    'login-no-account': 'Нет аккаунта? Зарегистрироваться',
    'login-social-divider': 'Или войдите через',
    'login-google': 'Google',
    'login-github': 'GitHub',
    'login-facebook': 'Facebook',
    'login-success': 'Успешный вход в систему!',
    'login-error': 'Неверный email/имя пользователя или пароль',
    
    // Forgot password modal
    'forgot-title': 'Сброс пароля',
    'forgot-description': 'Введите ваш email, и мы отправим инструкции по сбросу пароля.',
    'forgot-email-label': 'Email адрес',
    'forgot-email-placeholder': 'ваш.email@example.com',
    'forgot-button': 'Отправить ссылку',
    'forgot-success': 'Ссылка для сброса пароля отправлена на ваш email',
    'forgot-error': 'Пожалуйста, введите корректный email адрес',
    
    // Validation messages
    'validation-required': 'Это поле обязательно для заполнения',
    'validation-email': 'Пожалуйста, введите корректный email адрес',
    'validation-min-length': 'Должно быть не менее {min} символов',
    'validation-max-length': 'Должно быть не более {max} символов',
    
    // Error messages
    'error-network': 'Ошибка сети. Проверьте подключение',
    'error-server': 'Ошибка сервера. Попробуйте позже',
    'error-unknown': 'Произошла неизвестная ошибка',
    
    // Success messages
    'success-operation': 'Операция выполнена успешно',
    'success-saved': 'Изменения сохранены успешно',

    // Registration page
    'register-title': 'Регистрация - ServiceHub',
    'register-welcome': 'Создать аккаунт',
    'register-subtitle': 'Присоединяйтесь к нашему сообществу и откройте для себя удивительные услуги',
    'register-phone-label': 'Номер телефона (только Беларусь)',
    'register-phone-placeholder': '29 123 45 67',
    'register-phone-hint': 'Формат: 29 123 45 67 или 291234567',
    'register-phone-error': 'Пожалуйста, введите корректный белорусский номер телефона',
    'register-email-label': 'Email адрес',
    'register-email-placeholder': 'ваш.email@example.com',
    'register-email-error': 'Пожалуйста, введите корректный email адрес',
    'register-birthdate-label': 'Дата рождения',
    'register-birthdate-hint': 'Вам должно быть не менее 16 лет',
    'register-birthdate-error': 'Вам должно быть не менее 16 лет',
    'register-firstname-label': 'Имя',
    'register-firstname-placeholder': 'Иван',
    'register-firstname-error': 'Пожалуйста, введите ваше имя (минимум 2 символа)',
    'register-lastname-label': 'Фамилия',
    'register-lastname-placeholder': 'Иванов',
    'register-lastname-error': 'Пожалуйста, введите вашу фамилию (минимум 2 символа)',
    'register-middlename-label': 'Отчество (необязательно)',
    'register-middlename-placeholder': 'Иванович',
    'register-middlename-error': 'Пожалуйста, введите корректное отчество',
    'register-password-method-label': 'Способ создания пароля',
    'register-password-auto': 'Сгенерировать пароль автоматически',
    'register-password-manual': 'Установить свой пароль',
    'register-password-label': 'Пароль',
    'register-password-placeholder': 'Введите ваш пароль',
    'register-password-hint': 'Должен содержать: 8-20 символов, заглавные и строчные буквы, цифры, специальные символы',
    'register-password-strength': 'Надежность:',
    'register-password-weak': 'Слабая',
    'register-password-medium': 'Средняя',
    'register-password-strong': 'Сильная',
    'register-password-very-strong': 'Очень сильная',
    'register-password-error': 'Пароль должен содержать 8-20 символов, включая заглавные и строчные буквы, цифры и специальные символы',
    'register-confirm-password-label': 'Подтвердите пароль',
    'register-confirm-password-placeholder': 'Повторите ваш пароль',
    'register-confirm-password-error': 'Пароли не совпадают',
    'register-generated-password-label': 'Сгенерированный пароль',
    'register-generated-password-hint': 'Ваш пароль будет сгенерирован автоматически. Сохраните его в надежном месте!',
    'register-copy-password': 'Копировать пароль',
    'register-regenerate-password': 'Сгенерировать заново',
    'register-loading': 'Загрузка...',
    'register-copied': 'Скопировано!',
    'register-username-label': 'Имя пользователя',
    'register-username-placeholder': 'например, Ivanov123',
    'register-username-hint': 'Имя пользователя будет сгенерировано автоматически. У вас есть 5 попыток для перегенерации.',
    'register-username-error': 'Пожалуйста, введите корректное имя пользователя',
    'register-username-taken': 'Это имя пользователя уже занято',
    'register-username-available': 'Имя пользователя доступно',
    'register-generate-button': 'Сгенерировать',
    'register-attempts-counter': 'Осталось попыток перегенерации:',
    'register-terms-text': 'Я соглашаюсь с',
    'register-terms-link': 'Условиями обслуживания',
    'register-terms-and': 'и',
    'register-privacy-link': 'Политикой конфиденциальности',
    'register-terms-error': 'Вы должны принять условия использования',
    'register-button': 'Создать аккаунт',
    'register-button-disabled': 'Пожалуйста, заполните все обязательные поля',
    'register-login-link': 'Уже есть аккаунт? Войти',
    'register-success': 'Аккаунт успешно создан!',
    'register-error': 'Ошибка при создании аккаунта. Пожалуйста, попробуйте снова.',
    'register-error-phone-exists': 'Номер телефона уже зарегистрирован',
    'register-error-email-exists': 'Email уже зарегистрирован',
    
    // Terms modal
    'terms-title': 'Условия обслуживания',
    'terms-section-1-title': '1. Принятие условий',
    'terms-section-1-text': 'Используя ServiceHub, вы принимаете и соглашаетесь соблюдать условия и положения данного соглашения.',
    'terms-section-2-title': '2. Обязанности пользователя',
    'terms-section-2-text': 'Пользователи несут ответственность за сохранение конфиденциальности своего аккаунта и пароля.',
    'terms-section-3-title': '3. Изменения в услугах',
    'terms-section-3-text': 'ServiceHub оставляет за собой право изменять или прекращать предоставление услуг в любое время.',
    'terms-section-4-title': '4. Ограничение ответственности',
    'terms-section-4-text': 'ServiceHub не несет ответственности за любые косвенные, случайные или сопутствующие убытки.',
    'terms-last-updated': 'Последнее обновление: Декабрь 2024',
    'terms-accept-button': 'Я принимаю',

    // Feedback page
    'feedback-title': 'Отзывы - ServiceHub',
    'feedback-header': 'Отзывы клиентов',
    'feedback-subtitle': 'Поделитесь своим опытом использования наших услуг',
    'feedback-write-review': 'Написать отзыв',
    'feedback-form-description': 'Расскажите нам о вашем опыте использования наших услуг',
    'feedback-service-label': 'Выберите услугу',
    'feedback-loading-services': 'Загрузка услуг...',
    'feedback-service-hint': 'Вы можете оставить отзыв только о купленных услугах',
    'feedback-service-error': 'Пожалуйста, выберите услугу',
    'feedback-rating-label': 'Рейтинг',
    'feedback-rating-default': 'Выберите ваш рейтинг',
    'feedback-rating-5': 'Отлично - 5 звезд',
    'feedback-rating-4': 'Очень хорошо - 4 звезды',
    'feedback-rating-3': 'Хорошо - 3 звезды',
    'feedback-rating-2': 'Удовлетворительно - 2 звезды',
    'feedback-rating-1': 'Плохо - 1 звезда',
    'feedback-rating-error': 'Пожалуйста, выберите рейтинг',
    'feedback-title-label': 'Заголовок отзыва',
    'feedback-title-placeholder': 'Краткое описание вашего опыта',
    'feedback-title-error': 'Пожалуйста, введите заголовок отзыва (макс. 100 символов)',
    'feedback-text-label': 'Подробный отзыв',
    'feedback-text-placeholder': 'Поделитесь подробным описанием вашего опыта...',
    'feedback-text-error': 'Пожалуйста, введите подробный отзыв (50-1000 символов)',
    'feedback-text-hint': 'Будьте конкретны в том, что вам понравилось или не понравилось',
    'feedback-anonymous': 'Опубликовать анонимно',
    'feedback-anonymous-hint': 'Ваше имя не будет отображаться',
    'feedback-submit-button': 'Отправить отзыв',
    'feedback-submit-disabled': 'Пожалуйста, заполните все обязательные поля',
    'feedback-clear-button': 'Очистить форму',
    'feedback-chars-counter': '/100 символов',
    'feedback-chars-counter-min': '/1000 символов (минимум 50)',
    'feedback-recent-reviews': 'Последние отзывы',
    'feedback-total-reviews': 'Всего отзывов',
    'feedback-average-rating': 'Средний рейтинг',
    'feedback-filter-service': 'Фильтр по услуге:',
    'feedback-filter-rating': 'Фильтр по рейтингу:',
    'feedback-filter-all': 'Все услуги',
    'feedback-filter-all-ratings': 'Все рейтинги',
    'feedback-filter-rating-5': '5 звезд',
    'feedback-filter-rating-4': '4+ звезды',
    'feedback-filter-rating-3': '3+ звезды',
    'feedback-filter-rating-2': '2+ звезды',
    'feedback-filter-rating-1': '1 звезда',
    'feedback-stars': 'звезд',
    'feedback-star': 'звезда',
    'feedback-clear-filters': 'Очистить фильтры',
    'feedback-loading-reviews': 'Загрузка отзывов...',
    'feedback-no-reviews-title': 'Отзывов пока нет',
    'feedback-no-reviews-text': 'Будьте первым, кто поделится своим опытом!',
    'feedback-success': 'Отзыв успешно отправлен!',
    'feedback-error': 'Ошибка при отправке отзыва. Пожалуйста, попробуйте снова.',
    'feedback-error-not-purchased': 'Вы можете оставить отзыв только о купленных услугах',
    'feedback-error-duplicate': 'Вы уже оставляли отзыв об этой услуге',
    'feedback-delete-success': 'Отзыв успешно удален',
    'feedback-delete-error': 'Ошибка при удалении отзыва',
    'feedback-edit-success': 'Отзыв успешно обновлен',
    'feedback-edit-error': 'Ошибка при обновлении отзыва',
    
    // Review card text
    'feedback-review-by': 'от',
    'feedback-review-anonymous': 'Анонимный пользователь',
    'feedback-review-on': 'от',
    'feedback-review-service': 'Услуга:',
    'feedback-review-helpful': 'Полезно?',
    'feedback-review-helpful-count': 'человек считают это полезным',
    'feedback-review-reply': 'Ответ от ServiceHub:',
    'feedback-review-edit': 'Редактировать',
    'feedback-review-delete': 'Удалить',
    'feedback-review-report': 'Пожаловаться',
    'feedback-review-load-more': 'Загрузить больше отзывов',
    'feedback-review-no-more': 'Больше нет отзывов для загрузки',
    'feedback-review-sort-newest': 'Сначала новые',
    'feedback-review-sort-oldest': 'Сначала старые',
    'feedback-review-sort-highest': 'Сначала с высоким рейтингом',
    'feedback-review-sort-lowest': 'Сначала с низким рейтингом',
    'feedback-review-sort-most-helpful': 'Самые полезные',
    
    // Date formatting
    'feedback-date-just-now': 'Только что',
    'feedback-date-minutes-ago': 'минут назад',
    'feedback-date-hours-ago': 'часов назад',
    'feedback-date-days-ago': 'дней назад',
    'feedback-date-weeks-ago': 'недель назад',
    'feedback-date-months-ago': 'месяцев назад',
    'feedback-date-years-ago': 'лет назад',
    
    // Services list (for dropdown)
    'service-web-dev': 'Веб-разработка',
    'service-mobile-app': 'Мобильное приложение',
    'service-digital-marketing': 'Цифровой маркетинг',
    'service-ui-ux': 'UI/UX дизайн',
    'service-seo': 'SEO оптимизация',
    'service-cloud': 'Облачные решения',
    'service-ecommerce': 'E-commerce платформа',
    'service-crm': 'Разработка CRM',
    'service-analytics': 'Бизнес аналитика',

    // Favorites page
    'favorites-title': 'Мои избранные - ServiceHub',
    'favorites-header': 'Мои любимые услуги',
    'favorites-subtitle': 'Услуги, которые вы сохранили на потом',
    'favorites-clear-all': 'Очистить все избранное',
    'favorites-back-to-catalog': 'Назад в каталог',
    'favorites-loading': 'Загрузка избранного...',
    'favorites-empty-title': 'Нет избранных услуг',
    'favorites-empty-text': 'Просмотрите наш каталог и добавьте услуги в избранное!',
    'favorites-empty-button': 'Перейти в каталог',
    'favorites-remove': 'Удалить из избранного',
    'favorites-add-to-cart': 'Добавить в корзину',
    'favorites-view-details': 'Подробнее',
    'favorites-service-price': 'Цена:',
    'favorites-service-rating': 'Рейтинг:',
    'favorites-service-category': 'Категория:',
    'favorites-service-duration': 'Длительность:',
    'favorites-confirm-clear': 'Вы уверены, что хотите удалить все услуги из избранного?',
    'favorites-clear-success': 'Все избранное очищено',
    'favorites-clear-error': 'Ошибка при очистке избранного',
    'favorites-remove-success': 'Услуга удалена из избранного',
    'favorites-remove-error': 'Ошибка при удалении услуги',
    'favorites-add-cart-success': 'Услуга добавлена в корзину',
    'favorites-add-cart-error': 'Ошибка при добавлении в корзину',
    
    // Service categories
    'category-web-development': 'Веб-разработка',
    'category-mobile-apps': 'Мобильные приложения',
    'category-digital-marketing': 'Цифровой маркетинг',
    'category-design': 'Дизайн',
    'category-seo': 'SEO и аналитика',
    'category-cloud': 'Облачные сервисы',
    'category-consulting': 'Консалтинг',
    'category-support': 'Поддержка и обслуживание',
    
    // Price and duration
    'price-hourly': '/час',
    'price-project': '/проект',
    'price-monthly': '/месяц',
    'duration-hours': 'часов',
    'duration-days': 'дней',
    'duration-weeks': 'недель',
    'duration-months': 'месяцев',

    // Catalog page
    'catalog-title': 'Каталог услуг - ServiceHub',
    'catalog-header': 'Наш каталог услуг',
    'catalog-subtitle': 'Откройте для себя профессиональные услуги, адаптированные под ваши бизнес-потребности',
    'catalog-filter-category': 'Фильтр по категории',
    'catalog-search-placeholder': 'Поиск услуг по названию или описанию...',
    'catalog-sort-label': 'Сортировать по:',
    'catalog-sort-default': 'По умолчанию',
    'catalog-sort-name-asc': 'Название (А-Я)',
    'catalog-sort-name-desc': 'Название (Я-А)',
    'catalog-sort-price-asc': 'Цена (по возрастанию)',
    'catalog-sort-price-desc': 'Цена (по убыванию)',
    'catalog-sort-rating-desc': 'Рейтинг (по убыванию)',
    'catalog-advanced-filters': 'Расширенные фильтры',
    'catalog-price-range': 'Диапазон цен:',
    'catalog-min-price': 'Мин $',
    'catalog-max-price': 'Макс $',
    'catalog-price-to': 'до',
    'catalog-min-rating': 'Минимальный рейтинг:',
    'catalog-rating-any': 'Любой рейтинг',
    'catalog-rating-35': '3.5+ звезд',
    'catalog-rating-40': '4.0+ звезд',
    'catalog-rating-45': '4.5+ звезд',
    'catalog-rating-5': 'Только 5 звезд',
    'catalog-apply-filters': 'Применить фильтры',
    'catalog-reset-filters': 'Сбросить',
    'catalog-showing': 'Показано',
    'catalog-of': 'из',
    'catalog-services': 'услуг',
    'catalog-page': 'Страница',
    'catalog-previous': 'Назад',
    'catalog-next': 'Вперед',
    'catalog-items-6': '6 на странице',
    'catalog-items-9': '9 на странице',
    'catalog-items-12': '12 на странице',
    'catalog-items-15': '15 на странице',
    'catalog-loading': 'Загрузка услуг...',
    'catalog-no-results-title': 'Услуги не найдены',
    'catalog-no-results-text': 'Попробуйте изменить условия поиска или фильтры',
    'catalog-reset-all': 'Сбросить все фильтры',
    'catalog-add-to-favorites': 'Добавить в избранное',
    'catalog-remove-from-favorites': 'Удалить из избранного',
    'catalog-add-to-cart': 'Добавить в корзину',
    'catalog-view-details': 'Подробнее',
    'catalog-price': 'Цена:',
    'catalog-rating': 'Рейтинг:',
    'catalog-category': 'Категория:',
    'catalog-duration': 'Длительность:',
    'catalog-estimated': 'Примерно',
    'catalog-hours': 'часов',
    'catalog-days': 'дней',
    'catalog-weeks': 'недель',
    'catalog-popular': 'Популярное',
    'catalog-featured': 'Рекомендуемое',
    'catalog-new': 'Новое',
    'catalog-discount': 'Скидка',
    'catalog-clear-search': 'Очистить поиск',
    'catalog-applied-filters': 'Примененные фильтры:',
    'catalog-clear-all': 'Очистить все',
    'catalog-price-filter': 'Цена',
    'catalog-rating-filter': 'Рейтинг',
    'catalog-category-filter': 'Категория',
    
    // Service categories for catalog
    'category-all': 'Все категории',
    'category-web-dev': 'Веб-разработка',
    'category-mobile-app': 'Мобильные приложения',
    'category-digital-marketing': 'Цифровой маркетинг',
    'category-ui-ux': 'UI/UX дизайн',
    'category-seo': 'SEO оптимизация',
    'category-cloud': 'Облачные решения',
    'category-ecommerce': 'E-commerce',
    'category-crm': 'Разработка CRM',
    'category-analytics': 'Бизнес аналитика',
    'category-consulting': 'IT консалтинг',
    'category-support': 'Техническая поддержка',
    
    // Service card text
    'service-starts-at': 'От',
    'service-per-hour': '/час',
    'service-per-project': '/проект',
    'service-per-month': '/месяц',
    'service-features': 'Ключевые особенности:',
    'service-delivery': 'Срок выполнения:',
    'service-revisions': 'Правок включено:',
    'service-support': 'Поддержка:',
    'service-guarantee': 'Гарантия возврата',
    'service-included': 'Что включено',
    'service-not-included': 'Не включено',
    'service-requirements': 'Требования',
    'service-faq': 'Частые вопросы',
    'service-reviews': 'Отзывы',
    'service-order-now': 'Заказать сейчас',
    'service-contact-seller': 'Связаться с продавцом',
    'service-save-for-later': 'Сохранить на потом',
    'service-share': 'Поделиться',
    'service-report': 'Пожаловаться',
    
    // Price packages
    'package-basic': 'Базовый',
    'package-standard': 'Стандартный',
    'package-premium': 'Премиум',
    'package-enterprise': 'Корпоративный',
    'package-features': 'Особенности',
    'package-select': 'Выбрать пакет',
    
    // Success/error messages
    'catalog-favorite-added': 'Услуга добавлена в избранное',
    'catalog-favorite-removed': 'Услуга удалена из избранного',
    'catalog-cart-added': 'Услуга добавлена в корзину',
    'catalog-cart-error': 'Ошибка при добавлении в корзину',
    'catalog-load-error': 'Ошибка при загрузке услуг',
    'catalog-filter-applied': 'Фильтры применены',
    'catalog-filter-reset': 'Фильтры сброшены',
    'catalog-search-cleared': 'Поиск очищен',

    // Cart page
    'cart-title': 'Корзина покупок - ServiceHub',
    'cart-header': 'Корзина покупок',
    'cart-subtitle': 'Просмотрите и управляйте выбранными услугами',
    'cart-clear-all': 'Очистить корзину',
    'cart-add-more': 'Добавить больше услуг',
    'cart-loading': 'Загрузка товаров в корзине...',
    'cart-order-summary': 'Сводка заказа',
    'cart-subtotal': 'Промежуточный итог',
    'cart-tax': 'Налог (10%)',
    'cart-total': 'Итого',
    'cart-checkout': 'Перейти к оформлению',
    'cart-secure': 'Безопасная оплата',
    'cart-empty-title': 'Ваша корзина пуста',
    'cart-empty-text': 'Добавьте удивительные услуги, чтобы начать!',
    'cart-browse-services': 'Просмотреть услуги',
    'cart-item-remove': 'Удалить',
    'cart-item-quantity': 'Количество',
    'cart-item-price': 'Цена',
    'cart-item-total': 'Всего',
    'cart-item-duration': 'Длительность',
    'cart-item-service': 'Услуга',
    'cart-item-category': 'Категория',
    'cart-item-rating': 'Рейтинг',
    'cart-item-edit': 'Изменить',
    'cart-item-save': 'Сохранить на потом',
    'cart-item-move-to-favorites': 'Переместить в избранное',
    'cart-increase': 'Увеличить',
    'cart-decrease': 'Уменьшить',
    'cart-confirm-remove': 'Удалить этот товар из корзины?',
    'cart-confirm-clear': 'Очистить все товары из корзины?',
    'cart-remove-success': 'Товар удален из корзины',
    'cart-clear-success': 'Корзина очищена успешно',
    'cart-update-success': 'Корзина обновлена успешно',
    'cart-error': 'Ошибка при обновлении корзины',
    'cart-empty-checkout': 'Корзина пуста. Добавьте товары для продолжения.',
    'cart-login-required': 'Пожалуйста, войдите для оформления заказа',
    'cart-checkout-success': 'Оформление заказа успешно!',
    'cart-checkout-error': 'Ошибка при оформлении заказа',
    
    // Checkout modal
    'cart-modal-title': 'Заказ подтвержден!',
    'cart-modal-thanks': 'Спасибо за покупку!',
    'cart-modal-message': 'Ваш заказ успешно обработан. Письмо с подтверждением отправлено на ваш email.',
    'cart-modal-order-id': 'Номер заказа:',
    'cart-modal-total': 'Общая сумма:',
    'cart-modal-delivery': 'Примерная доставка:',
    'cart-modal-delivery-time': 'В течение 5-7 рабочих дней',
    'cart-modal-continue': 'Продолжить покупки',
    'cart-modal-view': 'Просмотреть детали заказа',
    
    // Payment methods
    'payment-credit-card': 'Кредитная карта',
    'payment-paypal': 'PayPal',
    'payment-bank-transfer': 'Банковский перевод',
    'payment-crypto': 'Криптовалюта',
    'payment-select-method': 'Выберите способ оплаты',
    'payment-card-number': 'Номер карты',
    'payment-card-expiry': 'Срок действия',
    'payment-card-cvv': 'CVV',
    'payment-card-name': 'Имя на карте',
    'payment-billing-address': 'Адрес для выставления счета',
    'payment-shipping-address': 'Адрес доставки',
    'payment-same-as-billing': 'Тот же, что и адрес для счета',
    'payment-terms': 'Я согласен с условиями использования',
    'payment-place-order': 'Оформить заказ',
    'payment-processing': 'Обработка платежа...',
    
    // Order status
    'order-status-pending': 'В ожидании',
    'order-status-processing': 'В обработке',
    'order-status-completed': 'Завершен',
    'order-status-cancelled': 'Отменен',
    'order-status-refunded': 'Возвращен',
    'order-date': 'Дата заказа',
    'order-status': 'Статус заказа',
    'order-tracking': 'Номер отслеживания',
    'order-invoice': 'Скачать счет',
    
    // Shipping options
    'shipping-standard': 'Стандартная (5-7 рабочих дней)',
    'shipping-express': 'Экспресс (2-3 рабочих дня)',
    'shipping-overnight': 'Ночная (1 рабочий день)',
    'shipping-free': 'Бесплатная доставка',
    'shipping-calculating': 'Расчет доставки...',
    'shipping-select': 'Выберите способ доставки',
    
    // Discount codes
    'discount-apply': 'Применить промокод',
    'discount-code': 'Промокод',
    'discount-apply-btn': 'Применить',
    'discount-remove': 'Удалить',
    'discount-invalid': 'Неверный промокод',
    'discount-applied': 'Скидка применена',
    'discount-expired': 'Промокод истек',

    // Admin page
    'admin-title': 'Панель администратора - ServiceHub',
    'admin-access-denied-title': 'Доступ запрещен',
    'admin-access-denied-text': 'Эта область доступна только администраторам.',
    'admin-back-to-home': 'На главную',
    'admin-header': 'Панель управления',
    'admin-subtitle': 'Управление услугами, отзывами, заказами и пользователями',
    'admin-total-services': 'Всего услуг',
    'admin-total-orders': 'Всего заказов',
    'admin-total-reviews': 'Всего отзывов',
    'admin-total-users': 'Всего пользователей',
    'admin-tab-services': 'Услуги',
    'admin-tab-feedback': 'Отзывы',
    'admin-tab-orders': 'Заказы',
    'admin-tab-users': 'Пользователи',
    'admin-services-title': 'Управление услугами',
    'admin-add-service': 'Добавить услугу',
    'admin-search-services': 'Поиск услуг...',
    'admin-feedback-title': 'Управление отзывами',
    'admin-filter-service': 'Фильтр по услуге:',
    'admin-filter-user': 'Фильтр по пользователю:',
    'admin-filter-rating': 'Фильтр по рейтингу:',
    'admin-filter-all': 'Все',
    'admin-stars': 'звезд',
    'admin-star': 'звезда',
    'admin-orders-title': 'Управление заказами',
    'admin-users-title': 'Управление пользователями',
    'admin-role-admin': 'Администраторы',
    'admin-role-user': 'Обычные пользователи',
    'admin-modal-add-service': 'Добавить услугу',
    'admin-modal-edit-service': 'Редактировать услугу',
    'admin-service-name': 'Название услуги',
    'admin-service-name-placeholder': 'Веб-дизайн',
    'admin-service-category': 'Категория',
    'admin-select-category': 'Выберите категорию',
    'admin-service-price': 'Цена ($)',
    'admin-service-price-placeholder': '299',
    'admin-service-rating': 'Рейтинг (1-5)',
    'admin-service-rating-placeholder': '4.7',
    'admin-service-description': 'Описание',
    'admin-service-description-placeholder': 'Опишите услугу...',
    'admin-chars-counter': '/500 символов',
    'admin-service-image': 'URL изображения',
    'admin-service-image-placeholder': '../assets/solution1.png',
    'admin-service-image-hint': 'Используйте относительный путь или полный URL',
    'admin-save-service': 'Сохранить услугу',
    'admin-cancel': 'Отмена',
    'admin-edit': 'Редактировать',
    'admin-delete': 'Удалить',
    'admin-view': 'Просмотреть',
    'admin-confirm-delete': 'Вы уверены, что хотите удалить этот элемент?',
    'admin-delete-success': 'Элемент успешно удален',
    'admin-delete-error': 'Ошибка при удалении элемента',
    'admin-save-success': 'Элемент успешно сохранен',
    'admin-save-error': 'Ошибка при сохранении элемента',
    'admin-load-error': 'Ошибка при загрузке данных',
    'admin-status-active': 'Активен',
    'admin-status-inactive': 'Неактивен',
    'admin-status-pending': 'В ожидании',
    'admin-status-completed': 'Завершен',
    'admin-status-cancelled': 'Отменен',
    'admin-no-data': 'Нет данных',
    'admin-loading': 'Загрузка...',
    'admin-actions': 'Действия',
    'admin-user-id': 'ID пользователя',
    'admin-user-email': 'Email',
    'admin-user-role': 'Роль',
    'admin-user-created': 'Создан',
    'admin-order-id': 'ID заказа',
    'admin-order-customer': 'Клиент',
    'admin-order-date': 'Дата заказа',
    'admin-order-status': 'Статус',
    'admin-order-total': 'Итого',
    'admin-feedback-id': 'ID отзыва',
    'admin-feedback-service': 'Услуга',
    'admin-feedback-user': 'Пользователь',
    'admin-feedback-rating': 'Рейтинг',
    'admin-feedback-date': 'Дата',
    'admin-service-id': 'ID услуги',
    'admin-service-image': 'Изображение',
    'admin-service-price': 'Цена',
    'admin-service-rating': 'Рейтинг',
    
    // Admin categories
    'category-design': 'Дизайн',
    'category-development': 'Разработка',
    'category-marketing': 'Маркетинг',
    'category-consulting': 'Консалтинг',
    'category-analytics': 'Аналитика',
    'category-support': 'Поддержка',
    'category-security': 'Безопасность',
    'category-cloud': 'Облако',
    'category-ai': 'ИИ',
    
    // Validation messages
    'admin-validation-required': 'Это поле обязательно',
    'admin-validation-price': 'Введите корректную цену',
    'admin-validation-rating': 'Рейтинг должен быть от 0 до 5',
    'admin-validation-url': 'Введите корректный URL',
    'admin-validation-description': 'Описание должно быть от 10 до 500 символов',

// Admin page (дополнительные тексты из JS кода)
'admin-view-feedback': 'Просмотреть отзывы',
'admin-no-results': 'Результаты не найдены',
'admin-try-adjusting-criteria': 'Попробуйте изменить критерии поиска',
'admin-service-meta': 'Метаданные услуги',
'admin-id': 'ID',
'admin-service-feedback-count': 'Отзывы',
'admin-feedback-details': 'Детали отзыва',
'admin-no-feedback-yet': 'Отзывов пока нет',
'admin-feedback-header': 'Отзывы для:',
'admin-total-reviews-for-service': 'Всего отзывов:',
'admin-user-info': 'Информация о пользователе',
'admin-feedback-text': 'Текст отзыва',
'admin-feedback-meta': 'Метаданные отзыва',
'admin-reported': 'Пожаловались',
'admin-order-info': 'Информация о заказе',
'admin-customer': 'Клиент',
'admin-phone': 'Телефон',
'admin-order-items': 'Товары',
'admin-order-item': 'Товар',
'admin-order-total': 'Всего:',
'admin-user-stats': 'Статистика пользователя',
'admin-reviews': 'отзывов',
'admin-orders': 'заказов',
'admin-spent': 'потрачено',
'admin-change-role': 'Изменить роль',
'admin-generate': 'Сгенерировать',
'admin-regenerate': 'Сгенерировать заново',
'admin-attempts-left': 'Осталось попыток перегенерации:',
'admin-copied': 'Скопировано!',
'admin-service-image-hint': 'Используйте относительный путь (напр., ../assets/service.jpg) или полный URL',
'admin-validation-image-url': 'Введите корректный URL изображения',
'admin-validation-name': 'Название услуги должно быть не менее 3 символов',
'admin-validation-description-min': 'Описание должно быть не менее 10 символов',
'admin-service-saved': 'Услуга успешно сохранена',
'admin-service-deleted': 'Услуга успешно удалена',
'admin-feedback-deleted': 'Отзыв успешно удален',
'admin-user-role-changed': 'Роль пользователя успешно изменена',
'admin-user-deleted': 'Пользователь успешно удален',
'admin-cannot-delete-admin': 'Нельзя удалить администраторов',
'admin-delete-user-confirm': 'У этого пользователя есть история заказов. Удаление также удалит все его заказы. Продолжить?',
'admin-delete-service-confirm': 'У этой услуги есть {count} отзывов. Удаление также удалит все связанные отзывы. Продолжить?',
'admin-saving': 'Сохранение...',
'admin-loading-data': 'Загрузка данных...',
'admin-access-checking': 'Проверка доступа...',
'admin-auth-unavailable': 'Служба аутентификации недоступна',
'admin-data-load-failed': 'Не удалось загрузить данные',
'admin-form-invalid': 'Исправьте ошибки валидации',
'admin-operation-failed': 'Ошибка выполнения операции',
'admin-close': 'Закрыть',
'admin-confirm': 'Подтвердить',
'admin-yes': 'Да',
'admin-no': 'Нет',
'admin-retry': 'Повторить',

'admin-category-web-development': 'Веб-разработка',
'admin-category-mobile-apps': 'Мобильные приложения',
'admin-category-digital-marketing': 'Цифровой маркетинг',
'admin-category-ui-ux-design': 'UI/UX дизайн',
'admin-category-seo': 'SEO и аналитика',
'admin-category-cloud-services': 'Облачные сервисы',
'admin-category-consulting': 'Консалтинг',
'admin-category-support': 'Поддержка',

'logout-success': 'Выход выполнен успешно',
'login-failed': 'Ошибка входа. Попробуйте снова.',
'registration-failed': 'Ошибка регистрации. Попробуйте снова.',
'welcome-back': 'С возвращением, {name}!',
'account-created': 'Аккаунт успешно создан!',

'cart-item-not-found': 'Товар не найден',
'cart-empty': 'Корзина уже пуста',
'cart-not-implemented': 'Здесь будут детали заказа',
'cart-item-price': 'Цена',
'cart-item-remove': 'Удалить',
'cart-item-category': 'Категория',
'cart-item-quantity': 'Количество',
'cart-item-total': 'Всего',
'cart-item-duration': 'Длительность',
'cart-item-service': 'Услуга',
'cart-item-rating': 'Рейтинг',
'cart-increase': 'Увеличить',
'cart-decrease': 'Уменьшить',

'catalog-login-required': 'Войдите, чтобы добавить в избранное',
'catalog-login-required-cart': 'Войдите, чтобы добавить в корзину',
'catalog-in-cart': 'В корзине',
'catalog-service-details': 'Детали для услуги',
'catalog-favorite-error': 'Ошибка обновления избранного',
'catalog-remove-from-favorites': 'Удалить из избранного',
'catalog-add-to-favorites': 'Добавить в избранное',
'catalog-loading': 'Загрузка услуг...',
'catalog-sort-name_asc': 'Название (А-Я)',
'catalog-sort-name_desc': 'Название (Я-А)',
'catalog-sort-price_asc': 'Цена (по возрастанию)',
'catalog-sort-price_desc': 'Цена (по убыванию)',
'catalog-sort-rating_desc': 'Рейтинг (по убыванию)',
'catalog-sort-default': 'По умолчанию',
'catalog-rating-0': 'Любой рейтинг',
'catalog-rating-35': '3.5+ звезд',
'catalog-rating-40': '4.0+ звезд',
'catalog-rating-45': '4.5+ звезд',
'catalog-rating-5': 'Только 5 звезд',
'catalog-items-6': '6 на странице',
'catalog-items-9': '9 на странице',
'catalog-items-12': '12 на странице',
'catalog-items-15': '15 на странице',

'favorites-login-required': 'Войдите, чтобы добавить в корзину',
'favorites-confirm-remove': 'Удалить эту услугу из избранного?',
'favorites-confirm-clear': 'Вы уверены, что хотите удалить все избранное?',
'favorites-empty': 'Нет избранных для очистки',
'favorites-back-to-catalog': 'Назад в каталог',
'favorites-remove': 'Удалить',
'favorites-add-to-cart': 'Добавить в корзину',
'favorites-view-details': 'Подробнее',
'favorites-service-price': 'Цена:',
'favorites-service-rating': 'Рейтинг:',
'favorites-service-category': 'Категория:',
'favorites-service-duration': 'Длительность:',
'favorites-loading': 'Загрузка избранного...',
'favorites-remove-tooltip': 'Удалить из избранного',

'feedback-load-error': 'Не удалось загрузить данные',
'feedback-no-purchased-services': 'Нет купленных услуг',
'feedback-service-default': 'Выберите услугу',
'feedback-sign-in-required': 'Войдите, чтобы оставить отзыв',
'feedback-admin-restricted': 'Администраторы не могут оставлять отзывы',
'feedback-purchase-required': 'Сначала нужно купить услугу',
'feedback-submitting': 'Отправка...',
'feedback-form-invalid': 'Исправьте все ошибки перед отправкой',
'feedback-unknown-service': 'Неизвестная услуга',
'feedback-customer': 'Клиент',
'feedback-login-required-helpful': 'Войдите, чтобы отметить как полезное',
'feedback-helpful-success': 'Отмечено как полезное!',
'feedback-helpful-error': 'Не удалось обновить',
'feedback-confirm-delete': 'Вы уверены, что хотите удалить этот отзыв?',
'feedback-loading-services': 'Загрузка услуг...',
'feedback-service-hint': 'Вы можете оставить отзыв только о купленных услугах',
'feedback-text-hint': 'Будьте конкретны в том, что вам понравилось или не понравилось',
'feedback-submit-disabled': 'Пожалуйста, заполните все обязательные поля',
'feedback-stars': 'звезд',
'feedback-star': 'звезда',
'feedback-loading-reviews': 'Загрузка отзывов...',

'login-toggle-password': 'Показать/Скрыть пароль',
'login-password-show': 'Показать пароль',
'login-password-hide': 'Скрыть пароль',
'login-signing-in': 'Вход в систему...',
'login-social-not-implemented': 'Вход через {provider} будет реализован здесь',
'forgot-sending': 'Отправка...',

// В русскую версию добавьте:
'register-password-show': 'Показать пароль',
'register-password-hide': 'Скрыть пароль',
'register-phone-operator-error': 'Должен быть действительным белорусским мобильным номером (29, 33, 44, 25)',
'register-name-format-error': 'Имя может содержать только буквы, пробелы, дефисы и апострофы',
'register-password-length-error': 'Пароль должен быть длиной 8-20 символов',
'register-password-common-error': 'Этот пароль слишком распространен. Выберите более надежный.',
'register-password-uppercase': 'Требуется заглавная буква. ',
'register-password-lowercase': 'Требуется строчная буква. ',
'register-password-number': 'Требуется цифра. ',
'register-password-special': 'Требуется специальный символ (@$!%*?&). ',
'register-username-length-error': 'Имя пользователя должно быть длиной 3-20 символов',
'register-username-format-error': 'Разрешены только буквы, цифры и подчеркивания',
'register-name-required': 'Пожалуйста, сначала введите ваше имя и фамилию',
'register-no-attempts-left': 'Попыток не осталось. Теперь вы можете ввести собственное имя пользователя.',
'register-attempts-hint': 'Имя пользователя сгенерировано автоматически. У вас осталось {attempts} попыток перегенерации.',
'register-manual-username-placeholder': 'Введите свое имя пользователя',
'register-manual-enabled': 'Ручной ввод включен',
'register-manual-hint': 'Теперь вы можете ввести собственное имя пользователя. Убедитесь, что оно уникальное!',
'register-creating': 'Создание аккаунта...',
'register-form-invalid': 'Исправьте все ошибки перед отправкой',
'register-copy-error': 'Не удалось скопировать пароль',

'theme-light': 'Светлая тема',
'theme-dark': 'Темная тема',
'theme-activated': '{theme} активирована',
'settings-reset-confirm': 'Вы уверены, что хотите сбросить все настройки по умолчанию?',
'settings-reset-success': 'Настройки сброшены по умолчанию',
'settings-language': 'Язык:',
'settings-theme': 'Тема:',
'theme-light': 'Светлая',
'theme-dark': 'Темная',

'user-settings': 'Настройки пользователя',
'user-username-placeholder': 'Введите имя пользователя',
'user-email-placeholder': 'Введите email',
'unknown-date': 'Неизвестно',
'change-language': 'Изменить язык',
'change-theme': 'Изменить тему',
'sign-in-to-save': 'Войдите, чтобы сохранить настройки',
'username-min-length': 'Имя пользователя должно быть не менее 3 символов',
'settings-saved': 'Настройки успешно сохранены',
'sign-in-to-reset': 'Войдите, чтобы сбросить настройки',
'settings-reset-success': 'Все настройки сброшены по умолчанию',
  }
};

function updateLanguageButtons(currentLang) {
  const langButtons = document.querySelectorAll('.lang-btn');
  if (langButtons.length > 0) {
    langButtons.forEach(btn => {
      if (btn.dataset.lang === currentLang) {
        btn.classList.add('active');
      } else {
        btn.classList.remove('active');
      }
    });
  }
}

function updateValidationMessages(lang) {
  const errorElements = document.querySelectorAll('.error-message');
  errorElements.forEach(element => {
    if (element.textContent) {
      const key = element.dataset.errorKey;
      if (key && i18Obj[lang] && i18Obj[lang][key]) {
        element.textContent = i18Obj[lang][key];
      }
    }
  });
}

function getTranslate(lang) {
  const elements = document.querySelectorAll('[data-i18n]');
  
  elements.forEach(element => {
    const key = element.dataset.i18n;
    if (i18Obj[lang] && i18Obj[lang][key]) {
      if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
        element.placeholder = i18Obj[lang][key];
      } else {
        element.textContent = i18Obj[lang][key];
      }
    }
  });
  
  document.querySelectorAll('[data-i18n-placeholder]').forEach(element => {
    const key = element.dataset.i18nPlaceholder;
    if (i18Obj[lang] && i18Obj[lang][key]) {
      element.placeholder = i18Obj[lang][key];
    }
  });
  
  updateLanguageButtons(lang);
  
  updateValidationMessages(lang);
  
  localStorage.setItem('lang', lang);
  
  const event = new CustomEvent('langChanged', { detail: { lang } });
  document.dispatchEvent(event);
}

document.addEventListener('DOMContentLoaded', () => {
  const savedLang = localStorage.getItem('lang') || 'en';
  getTranslate(savedLang);
});

window.i18Obj = i18Obj;
window.getTranslate = getTranslate;
window.updateLanguageButtons = updateLanguageButtons;
window.updateValidationMessages = updateValidationMessages;